# Copyright (c) 2025 Geoffrey Huntley <ghuntley@ghuntley.com>. All rights reserved.
# SPDX-License-Identifier: Proprietary

keys:
  - &user_ghuntley age1sc7xejzhlq03wae7q4lte204a0lhz58y6p6skallk2204j8gcqpq6e67vq # ghuntley user key
  - &host_hammer age1htfhvk24zdukf0f4ka2hyeynwl5pyn2awe9rgg7dw3xur4rxqajsfdya23 # lathe SSH host key

creation_rules:
  # Workbench machine secrets
  - path_regex: hammer\.yaml$
    key_groups:
      - age:
          - *user_ghuntley
          - *host_hammer
