# Copyright (c) 2022 Geoffrey Huntley <ghuntley@ghuntley.com>. All rights reserved.
# SPDX-License-Identifier: Proprietary

name: "Build"
on:
  pull_request:
  push:
jobs:
  tests:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v17
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: cachix/cachix-action@v10
        with:
          name: ghuntley
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - run: nix-build
      - run: nix-shell --run "echo OK"
