# Copyright (c) 2022 Geoffrey Huntley <ghuntley@ghuntley.com>. All rights reserved.
# SPDX-License-Identifier: Proprietary

name: "//ops/dns: terraform plan"
on:
  push:
    branches:
      - '!trunk'
  pull_request:
  workflow_dispatch:

# Cancel in-progress runs for pull requests when developers push
# additional changes
concurrency:
  group: ${{ github.workflow }}-ops-dns-plan-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

permissions:
  issues: write
  pull-requests: write

jobs:
  ops-dns-plan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v20
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - uses: JRMurr/direnv-nix-action@v2
        with:
          install-nix: "false"
          cache-store: "false"

      - run: direnv exec . deploy-dns plan > $GITHUB_STEP_SUMMARY
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.TFSTATE_GOOGLE_CREDENTIALS }}
          TF_VAR_cloudflare_email: ${{ secrets.TF_VAR_cloudflare_email }}
          TF_VAR_cloudflare_api_key: ${{ secrets.TF_VAR_cloudflare_api_key }}
          TF_VAR_com_ghuntley_cloudflare_zone_id: ${{ secrets.TF_VAR_com_ghuntley_cloudflare_zone_id }}
          TF_VAR_dev_ghuntley_cloudflare_zone_id: ${{ secrets.TF_VAR_dev_ghuntley_cloudflare_zone_id }}
          TF_VAR_net_ghuntley_cloudflare_zone_id: ${{ secrets.TF_VAR_net_ghuntley_cloudflare_zone_id }}
          TF_VAR_com_ghuntley_ipv4: ${{ secrets.TF_VAR_com_ghuntley_ipv4 }}
          TF_VAR_com_ghuntley_ipv6: ${{ secrets.TF_VAR_com_ghuntley_ipv6 }}
          TF_VAR_dev_ghuntley_ipv4: ${{ secrets.TF_VAR_dev_ghuntley_ipv4 }}
          TF_VAR_dev_ghuntley_ipv6: ${{ secrets.TF_VAR_dev_ghuntley_ipv6 }}
          TF_VAR_net_ghuntley_ipv4: ${{ secrets.TF_VAR_net_ghuntley_ipv4 }}
          TF_VAR_net_ghuntley_ipv6: ${{ secrets.TF_VAR_net_ghuntley_ipv6 }}


      - uses: GrantBirki/comment@v2.0.3
        with:
          file: $GITHUB_STEP_SUMMARY
          issue-number: ${{ github.event.number }}
