# Copyright (c) 2022 Geoffrey Huntley <ghuntley@ghuntley.com>. All rights reserved.
# SPDX-License-Identifier: Proprietary

name: "//ops/dns: terraform apply"
on:
  push:
    branches:
      - trunk
  workflow_dispatch:

# Cancel in-progress runs for pull requests when developers push
# additional changes
concurrency:
  group: ${{ github.workflow }}-ops-dns-apply-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  ops-dns-apply:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v20
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - uses: JRMurr/direnv-nix-action@v2
        with:
          install-nix: "false"
          cache-store: "false"

      - run: direnv exec . deploy-dns apply -auto-approve | tee $GITHUB_STEP_SUMMARY
        env:
          TF_VAR_cloudflare_email: ${{ secrets.TF_VAR_cloudflare_email }}
          TF_VAR_cloudflare_api_key: ${{ secrets.TF_VAR_cloudflare_api_key }}
          TF_VAR_com_ghuntley_cloudflare_zone_id: ${{ secrets.TF_VAR_com_ghuntley_cloudflare_zone_id }}
          TF_VAR_dev_ghuntley_cloudflare_zone_id: ${{ secrets.TF_VAR_dev_ghuntley_cloudflare_zone_id }}
          TF_VAR_net_ghuntley_cloudflare_zone_id: ${{ secrets.TF_VAR_net_ghuntley_cloudflare_zone_id }}
          TF_VAR_com_ghuntley_ipv4: ${{ secrets.TF_VAR_com_ghuntley_ipv4 }}
          TF_VAR_com_ghuntley_ipv6: ${{ secrets.TF_VAR_com_ghuntley_ipv6 }}
          TF_VAR_dev_ghuntley_ipv4: ${{ secrets.TF_VAR_dev_ghuntley_ipv4 }}
          TF_VAR_dev_ghuntley_ipv6: ${{ secrets.TF_VAR_dev_ghuntley_ipv6 }}
          TF_VAR_net_ghuntley_ipv4: ${{ secrets.TF_VAR_net_ghuntley_ipv4 }}
          TF_VAR_net_ghuntley_ipv6: ${{ secrets.TF_VAR_net_ghuntley_ipv6 }}
