# Copyright (c) 2022 Geoffrey Huntley <ghuntley@ghuntley.com>. All rights reserved.
# SPDX-License-Identifier: Proprietary

name: "//services/dev-ghuntley: coder push"

on:
  push:
    branches:
      - trunk
    paths:
      - 'services/dev-ghuntley/templates/**'
      - '.github/workflows/services-dev-ghuntley-templates-push.yml'

  workflow_dispatch:
  schedule:
    # * is a special character in YAML so you have to quote this string
    # run this every day at 4:00am
    - cron: "0 4 * * *"

# Cancel in-progress runs for pull requests when developers push
# additional changes
concurrency:
  group: ${{ github.workflow }}-services-dev-ghuntley-templates-push-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  services-dev-ghuntley-templates-push:
    runs-on: nscloud-amd64
        steps:
        - name: Checkout
          uses: actions/checkout@v3
        - name: Get latest commit hash
          id: latest_commit
          run: echo "hash=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
        - name: Get commit title
           id: commit_title
           run: echo "title=$(git log -1 --pretty=%s)" >> $GITHUB_OUTPUT


        - name: Update Coder Template
            uses: matifali/update-coder-template@v3
            with:
                id: ubuntu
                dir: services/dev-ghuntley/templates/ubuntu
                url: https://ghuntley.dev
                name: ${{ steps.latest_commit.outputs.hash }}
                message: ${{ steps.commit_title.outputs.title }}
                coder_session_token: ${{ secrets.DEV_GHUNTLEY_CODER_SESSION_TOKEN }}
